coa/app/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views, item, sales

urlpatterns = [
    path('', views.login_view,name='login'),
    path('login', views.login_view,name='login'),
    path('logout', views.logout_view, name='logout'),
    path('dashboard', views.dashboard,name='dashboard'),
    path('statistics', views.statistics,name='statistics'),
    path('prediction', views.prediction,name='prediction'),
    path('preview', views.order_preview,name='order_preview'),
    path('place-order', views.order_place,name='order_place'),
    path('order-clear', views.order_clear,name='order_clear'),
    path('change-order-clear', views.change_order_status,name='change_order_status'),
    path('order/<str:token>', views.order_view,name='order_view'),
    path('order-download/<str:token>', views.order_download,name='order_download'),
    path('add-new-order', views.order_add_new,name='order_add_new'),
    path('add-new-order/preview', views.order_add_new_preview,name='order_add_new_preview'),
    path('add-new-order/generate', views.order_add_new_generate,name='order_add_new_generate'),
    path('history', views.order_history,name='order_history'),
    path('store', views.store,name='store'),
    path('generate_store_prediction_data', views.generate_store_prediction_data,name='generate_store_prediction_data'),
    path('change-chart/<str:token>/<int:cid>', views.change_chart_data, name='change_chart_data'),
    #get category's subcategories
    path('subcategories/<int:pk>', views.subcategories, name='subcategories'),
    #items
    path('item/listing', item.item_list, name='item_list'),
    path('item/status', item.change_item_status, name='change_item_status'),
    path('item/view/<str:token>', item.item_view, name='item_view'),
    path('item/new', item.item_create, name='item_new'),  
    path('item/edit/<str:token>', item.item_update, name='item_edit'),
    path('item/delete/<str:token>', item.item_delete, name='item_delete'),
    #sales data
    path('sales/listing', sales.sales_list, name='sales_list'),
    path('sales/status', sales.change_sales_status, name='change_sales_status'),
    path('sales/view/<int:pk>', sales.sales_view, name='sales_view'),
    path('sales/new', sales.sales_create, name='sales_new'),  
    path('sales/edit/<int:pk>', sales.sales_update, name='sales_edit'),
    path('sales/delete/<int:pk>', sales.sales_delete, name='sales_delete'),
    path('sales/import/upload', sales.sales_import_upload, name='sales_import_upload'),
    path('sales/import/list', sales.sales_import_list, name='sales_import_list'),
] 

coa/coa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coa/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, PermissionsMixin
from django.utils.translation import ugettext_lazy as _
import uuid
from django.contrib.auth.models import User
# from django.contrib.postgres.fields import JSONField
from django.db.models import JSONField

#Category Model
class Category(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    name        = models.CharField(max_length=255, unique=True)
    publish     = models.BooleanField(default = True)
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt   = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

#Sub Category Model
class Subcategory(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    category    = models.ForeignKey(Category, on_delete=models.CASCADE)
    name        = models.CharField(max_length=255)
    publish     = models.BooleanField(default = True)
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt   = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Sub Category'
        verbose_name_plural = 'Sub Categories'

#Family Model
class Family(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    name        = models.CharField(max_length=255, unique=True)
    publish     = models.BooleanField(default = True)
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt   = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Family'
        verbose_name_plural = 'Families'

#Store Model
class Store(models.Model):
    token           = models.UUIDField(default= uuid.uuid4)
    user            = models.ForeignKey(User, on_delete=models.CASCADE)
    name            = models.CharField(max_length=255)
    address         = models.CharField(max_length=255)
    city            = models.CharField(max_length=255)
    state           = models.CharField(max_length=255)
    zipcode         = models.CharField(max_length=255)
    phone           = models.CharField(max_length=255,blank = True, null=True)
    publish         = models.BooleanField(default = True)
    createdAt       = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt       = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Store'
        verbose_name_plural = 'Stores'

#Supplier Model
class Supplier(models.Model):
    token           = models.UUIDField(default= uuid.uuid4)
    name            = models.CharField(max_length=255)
    address         = models.CharField(max_length=255)
    city            = models.CharField(max_length=255)
    state           = models.CharField(max_length=255)
    zipcode         = models.CharField(max_length=255)
    email           = models.EmailField(max_length=255)
    phone           = models.CharField(max_length=255,blank = True, null=True)
    moq             = models.FloatField(blank = True, null=True)
    publish         = models.BooleanField(default = True)
    createdAt       = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt       = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Supplier'
        verbose_name_plural = 'Suppliers'

#Item Model
class Item(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    store       = models.ForeignKey(Store, on_delete=models.CASCADE)
    image       = models.ImageField(null=True, blank=True, upload_to="items/")
    category    = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    supplier    = models.ForeignKey(Supplier, on_delete=models.CASCADE, blank = True, null=True)
    name        = models.CharField(max_length=255)
    sku         = models.CharField(max_length=255)
    price       = models.FloatField()
    moq         = models.IntegerField(blank = True, null=True, default=1)
    uom         = models.CharField(max_length=255, choices=(('mm','Millimeter'),('cm','Centimeters'),('m','Meter'),('mg','Milligram'),('g','Gram'),('kg','Kilograms'),('mel','Milliliter'),('l','Liter'),('q','Quantity')), blank = True, null=True)
    publish     = models.BooleanField(default = True)
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt   = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Items'

#Sales Data Model
class Sales(models.Model):
    item        = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity    = models.IntegerField()
    revenue     = models.FloatField(blank = True, null=True)
    updatedOn   = models.DateField()
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.item.name

    class Meta:
        verbose_name = 'Sales Data'
        verbose_name_plural = 'Sales Datas'

#Stock Data Model
class Stock(models.Model):
    item        = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity    = models.IntegerField()
    updatedOn   = models.DateField()
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.item.name

    class Meta:
        verbose_name = 'Stock Data'
        verbose_name_plural = 'Stock Datas'


#Store charts
class Salescharts(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    store       = models.ForeignKey(Store, on_delete=models.CASCADE)
    chart1      = JSONField(null=True, blank = True)
    chart2      = JSONField(null=True, blank = True)
    chart3      = JSONField(null=True, blank = True)
    chart4      = JSONField(null=True, blank = True)
    chart5      = JSONField(null=True, blank = True)
    chart6      = JSONField(null=True, blank = True)
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt   = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return str(self.store)

    class Meta:
        verbose_name = 'Sales Chart'
        verbose_name_plural = 'Sales Charts'

#Weekly Sales Data Model
class WeeklySales(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    store       = models.ForeignKey(Store, on_delete=models.CASCADE)
    category    = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    mon         = models.FloatField()
    tue         = models.FloatField()
    wed         = models.FloatField()
    thu         = models.FloatField()
    fri         = models.FloatField()
    sat         = models.FloatField()
    sun         = models.FloatField()
    tot         = models.FloatField()
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return str(self.store)+' - '+str(self.category)+' - '+str(self.subcategory)+' - '+str(self.createdAt)

    class Meta:
        verbose_name = 'Weekly Sales Data'
        verbose_name_plural = 'Weekly Sales Data'

#Weekly Item Avg Data
class WeeklyItemsAvg(models.Model):
    salesweek   = models.ForeignKey(WeeklySales, on_delete=models.CASCADE)
    item        = models.ForeignKey(Item, on_delete=models.CASCADE)
    avg         = models.FloatField()
    ratio       = models.FloatField()
    mon         = models.FloatField()
    tue         = models.FloatField()
    wed         = models.FloatField()
    thu         = models.FloatField()
    fri         = models.FloatField()
    sat         = models.FloatField()
    sun         = models.FloatField()
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return str(self.item)

    class Meta:
        verbose_name = 'Item Weekly Avg'
        verbose_name_plural = 'Item Weekly Avg'

#Order Model
class Order(models.Model):
    token           = models.UUIDField(default= uuid.uuid4)
    store           = models.ForeignKey(Store, on_delete=models.CASCADE)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory     = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    is_placed       = models.BooleanField(default = False)
    activate_day    = models.CharField(max_length=255)
    order_type      = models.CharField(max_length=255, choices=(('Prediction','Prediction'),('Custom','Custom')),default = 'Prediction')
    createdAt       = models.DateTimeField(auto_now_add=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return str(self.store)+' - '+str(self.category)+' - '+str(self.subcategory)+' - '+str(self.createdAt)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

#Order Item Model
class OrederItem(models.Model):
    order           = models.ForeignKey(Order, on_delete=models.CASCADE)

coa/templates/item/add.html
{% extends "base.html" %}

{% block title %}Add New Item{% endblock %}

{% block pagetitle %}Add New Item{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
    <li class="breadcrumb-item"><a href="{% url 'item_list' %}">Item Listing</a></li>
    <li class="breadcrumb-item active">Add New Item</li>
{% endblock %}

{% load static %}

{% block content %}

<section class="content">

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
            <div class="alert alert-danger">{{ message|safe }}</div><br/>
            {% else%}
            <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div><br/>
            {% endif %}
        {% endfor %}
    {% endif %}

    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <h3 class="card-title">Item Information</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form class="form-horizontal" method="POST" enctype="multipart/form-data">
                    <div class="card-body">
                        {% csrf_token %}

                        {% if form.errors %}
                            <div class="alert alert-danger">
                                <h4>Please fix the following errors</h4>
                                <ul>
                                {% for field in form %}
                                    {% if field.errors %}
                                        {% for error in field.errors %}
                                            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                                </ul>
                                {% if form.non_field_errors %}
                                    {{ form.non_field_errors }}
                                {% endif %}
                            </div>
                        {% endif %}
                        
                        {% for field in form.visible_fields %}

                            <div class="form-group row">
                                <label for="id_{{ field.name }}" class="col-sm-2 col-form-label">{{ field.label|upper}} {% if field.field.required %}<span class="required">*</span>{% endif %} </label>
                                <div class="col-sm-10">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    {% for hidden_field in form.hidden_fields %}
                        {{ hidden_field }}
                    {% endfor %}
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <input type="submit" value="Save" class="btn btn-info" name="save">
                        <a href="{% url 'item_list' %}" class="btn btn-default">Cancel</a>
                    </div>
                    <!-- /.card-footer -->
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock  %}

coa/templates/item/detail.html
{% extends "base.html" %}

{% block title %}View Item{% endblock %}

{% block pagetitle %}View Item{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
    <li class="breadcrumb-item"><a href="{% url 'item_list' %}">Item Listing</a></li>
    <li class="breadcrumb-item active">View Item</li>
{% endblock %}

{% load static %}

{% block content %}

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card card-solid">
      <div class="card-body">
        <div class="row">

          <div class="col-12 col-sm-6">
            <h3 class="d-inline-block d-sm-none">{{object.name}}</h3>
            <div class="col-12">
              {% if object.image %}
                <img class="product-image" src="{{object.image.url}}">
              {% else %}
                <img class="product-image" src="{% static 'no-image.jpg' %}">
              {% endif %}
            </div>
          </div> 

          <div class="col-12 col-sm-6">
            <h3 class="my-3">{{object.name}}</h3>
            <hr>
            
            <h4>SKU</h4>
            <p>{{object.sku}}</p>

            <h4>Unit Pricing</h4>
            <p>{{object.price}}</p>

            <h4>MOQ</h4>
            <p>{{object.moq}}</p>

            <h4>Unit of Measurement</h4>
            <p>{{object.get_uom_display}}</p>

            <h4>Category</h4>
            <p>{{object.category}}</p>

            <h4>Sub Category</h4>
            <p>{{object.subcategory}}</p>

            <h4>Supplier</h4>
            <p>{{object.supplier}}</p>
            
          </div>
        </div>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->

  </section>
{% endblock  %}

coa/templates/item/list.html
{% extends "base.html" %}

{% block title %}Items{% endblock %}

{% block pagetitle %}Items{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<li class="breadcrumb-item active">Items</li>
{% endblock %}

{% load static %}

{% block content %}
<section class="content">
	<div class="container-fluid">
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == 'error' %}
				<div class="alert alert-danger">{{ message|safe }}</div><br/>
				{% else%}
				<div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div><br/>
				{% endif %}
			{% endfor %}
		{% endif %}

		<div class="row">
				<div class="col-12">
		<div class="card">
				<div class="card-header">
					<h3 class="card-title">Filter</h3>
				</div>
				<!-- /.card-header -->
				<div class="card-body">
					<form role="form" method="POST" id="filter_item_form">
					{% csrf_token %}
					<div class="row">
						<div class="col-sm-3">
							<!-- select -->
							<div class="form-group">
								<label>Search</label>
								<input type="text" name="search" id="search" class="form-control" placeholder="Search by SKU ID and Name" value="{% if item_Post.search%}{{item_Post.search}}{% endif %}">
							</div>
						</div>

						<div class="col-sm-4">
							<!-- select -->
							<div class="form-group">
								<label>Category</label>
								<select class="custom-select" name="category" id="id_category">
								<option value="">-- Select Category --</option>
								{% for cat in categories%}
									<option value="{{cat.id}}" {% if item_Post.category|slugify == cat.id|slugify %} selected {% endif %}>{{cat.name}}</option>
								{% endfor %}
								
								</select>
							</div>
						</div>
						<div class="col-sm-3">
						<div class="form-group">
							<label>Sub Category</label>
							<select class="custom-select" name="subcategory" id="id_subcategory">
							<option value="">-- Select Sub Category --</option>
							{% for sub in subcategories %}
								<option value="{{sub.id}}" {% if item_Post.subcategory|slugify == sub.id|slugify %} selected {% endif %}>{{sub.name}}</option>
							{% endfor %}
							</select>
						</div>
						</div>
					<div class="col-sm-2">
						<div class="form-group" style="margin-top:30px;">
							<button type="button" class="btn btn-info" onclick="ItemFormSeach('search');">Search</button>
							<button type="button" class="btn btn-default" onclick="ItemFormSeach('clear');">Clear</button>
							<input type="hidden" name="search_action" id="search_action" value="search">
						</div>
					</div>
					</div>
				</form>
				</div>
				<!-- /.card-body -->
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Item Listing</h3> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						<div class="btn-group" id="action_btn" style="display:none">
							<button type="button" class="btn btn-default">Action</button>
							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
							</button>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item"  href="javascript:ActionForm('delete')">Delete Selected Items</a></li>
							</ul>
						</div>
						<div class="card-tools">
			 				<a href="{% url 'item_new' %}" class="btn btn-block btn-primary"><i class="fas fa-plus"></i> &nbsp Add New Item</a>
						</div>
					</div>
					<!-- /.card-header -->
					{% if object_list %}
					<div class="card-body table-responsive">
						<form method="POST" id="form_list" action="{% url 'change_item_status' %}">
							{% csrf_token %}
							<table id="item_list" class="table table-bordered table-striped">
								<thead>
								<tr class="bg-primary">
									<th class="text-center"><input type="checkbox" name="chk_all" id="chk_all" value="all"></th>
									<th >Image</th>
									<th class="text-center">
										{% if order_by == 'sku' %}
											{% if direction == 'asc' %}
												<a href="?order_by=sku&direction=desc" style="color:aliceblue">SKU ID &nbsp;&nbsp;<i class='fas fa-arrow-up'></i></a>
											{% else %}
												<a href="?order_by=sku&direction=asc" style="color:aliceblue">SKU ID &nbsp;&nbsp;<i class='fas fa-arrow-down'></i></a>
											{% endif %}
										{% else %}
											<a href="?order_by=sku&direction=asc" style="color:aliceblue">SKU ID</a>
										{% endif %}
									</th>
									<th class="text-center">
										{% if order_by == 'name' %}
											{% if direction == 'asc' %}
												<a href="?order_by=name&direction=desc" style="color:aliceblue">SKU Name &nbsp;&nbsp;<i class='fas fa-arrow-up'></i></a>
											{% else %}
												<a href="?order_by=name&direction=asc" style="color:aliceblue">SKU Name &nbsp;&nbsp;<i class='fas fa-arrow-down'></i></a>
											{% endif %}
										{% else %}
											<a href="?order_by=name&direction=asc" style="color:aliceblue">SKU Name</a>
										{% endif %}
									</th>

									<th class="text-center">
										{% if order_by == 'price' %}
											{% if direction == 'asc' %}
												<a href="?order_by=price&direction=desc" style="color:aliceblue">Unit Price &nbsp;&nbsp;<i class='fas fa-arrow-up'></i></a>
											{% else %}
												<a href="?order_by=price&direction=asc" style="color:aliceblue">Unit Price &nbsp;&nbsp;<i class='fas fa-arrow-down'></i></a>
											{% endif %}
										{% else %}
											<a href="?order_by=price&direction=asc" style="color:aliceblue">Unit Price</a>
										{% endif %}
									</th>

									<th class="text-center">
										{% if order_by == 'moq' %}
											{% if direction == 'asc' %}
												<a href="?order_by=moq&direction=desc" style="color:aliceblue">MOQ &nbsp;&nbsp;<i class='fas fa-arrow-up'></i></a>
											{% else %}
												<a href="?order_by=moq&direction=asc" style="color:aliceblue">MOQ &nbsp;&nbsp;<i class='fas fa-arrow-down'></i></a>
											{% endif %}
										{% else %}
											<a href="?order_by=moq&direction=asc" style="color:aliceblue">MOQ</a>
										{% endif %}
									</th>

									<th class="text-center">
										{% if order_by == 'uom' %}
											{% if direction == 'asc' %}
												<a href="?order_by=uom&direction=desc" style="color:aliceblue">UOM &nbsp;&nbsp;<i class='fas fa-arrow-up'></i></a>
											{% else %}
												<a href="?order_by=uom&direction=asc" style="color:aliceblue">UOM &nbsp;&nbsp;<i class='fas fa-arrow-down'></i></a>
											{% endif %}
										{% else %}
											<a href="?order_by=uom&direction=asc" style="color:aliceblue">UOM</a>
										{% endif %}
									</th>
									
									<th class="text-center">
										{% if order_by == 'category' %}
											{% if direction == 'asc' %}
												<a href="?order_by=category&direction=desc" style="color:aliceblue">Category &nbsp;&nbsp;<i class='fas fa-arrow-up'></i></a>
											{% else %}
												<a href="?order_by=category&direction=asc" style="color:aliceblue">Category &nbsp;&nbsp;<i class='fas fa-arrow-down'></i></a>
											{% endif %}
										{% else %}
											<a href="?order_by=category&direction=asc" style="color:aliceblue">Category</a>
										{% endif %}
									</th>

									<th class="text-center">
										{% if order_by == 'subcategory' %}
											{% if direction == 'asc' %}
												<a href="?order_by=subcategory&direction=desc" style="color:aliceblue">Sub Category &nbsp;&nbsp;<i class='fas fa-arrow-up'></i></a>
											{% else %}
												<a href="?order_by=subcategory&direction=asc" style="color:aliceblue">Sub Category &nbsp;&nbsp;<i class='fas fa-arrow-down'></i></a>
											{% endif %}
										{% else %}
											<a href="?order_by=subcategory&direction=asc" style="color:aliceblue">Sub Category</a>
										{% endif %}
									</th>
									<th class="text-center">
										{% if order_by == 'supplier' %}
											{% if direction == 'asc' %}
												<a href="?order_by=supplier&direction=desc" style="color:aliceblue">Supplier &nbsp;&nbsp;<i class='fas fa-arrow-up'></i></a>
											{% else %}
												<a href="?order_by=supplier&direction=asc" style="color:aliceblue">Supplier &nbsp;&nbsp;<i class='fas fa-arrow-down'></i></a>
											{% endif %}
										{% else %}
											<a href="?order_by=supplier&direction=asc" style="color:aliceblue">Supplier</a>
										{% endif %}
									</th>
									<th class="text-center">Action</th>
								</tr>
								</thead>
								<tbody>
									{% for item in object_list %}
										<tr>
											<td class="text-center">
												<input type="checkbox" id="id_{{item.token}}" name="records" class="chk" value="{{item.token}}">
											</td>
											<td>
												{% if item.image %}
													<img class="product-image" src="{{item.image.url}}" style="width:50px; height:50px;">
												{% else %}
													<img class="product-image" src="{% static 'no-image.jpg' %}" style="width:50px; height:50px;">
												{% endif %}
											</td>
											<td class="text-center">{{item.sku}}</td>
											<td class="text-center">{{item.name}}</td>
											<td class="text-center">{{item.price}}</td>
											<td class="text-center">{{item.moq}}</td>
											<td class="text-center">{{item.get_uom_display}}</td>
											<td class="text-center">{{item.category}}</td>
											<td class="text-center">{{item.subcategory}}</td>
											<td class="text-center">{% if item.supplier %}{{item.supplier}}{% else %}-{% endif %}</td>
											<td class="text-center">
												<a href="{% url 'item_view' item.token %}" class="btn btn-sm btn-secondary" title="View"><i class="fas fa-eye"></i> View</a>
												<a href="{% url 'item_edit' item.token %}" class="btn btn-sm btn-info" title="Edit"><i class="fas fa-pencil-alt"></i> Edit</a>
												<a href="{% url 'item_delete' item.token %}" class="btn btn-sm btn-danger" title="Delete"><i class="fas fa-trash"></i> Delete</a>
											</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
							<input type="hidden" name="action_on" id="action_on">
						</form>
					</div>
					<!-- /.card-body -->
					<div class="card-footer clearfix">

							{% if object_list.has_other_pages %}
							<ul class="pagination pagination-sm m-0 float-right">
								{% if object_list.has_previous %}
								<li class="page-item"><a class="page-link" href="?order_by={{order_by}}&direction={{direction}}&page={{ object_list.previous_page_number }}">&laquo;</a></li>
								{% else %}
								<li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
								{% endif %}
								{% for i in object_list.paginator.page_range %}
								{% if object_list.number == i %}
									<li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
								{% else %}
									<li class="page-item"><a class="page-link" href="?order_by={{order_by}}&direction={{direction}}&page={{ i }}">{{ i }}</a></li>
								{% endif %}
								{% endfor %}
								{% if object_list.has_next %}
								<li class="page-item"><a class="page-link" href="?order_by={{order_by}}&direction={{direction}}&page={{ object_list.next_page_number }}">&raquo;</a></li>
								{% else %}
								<li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
								{% endif %}
							</ul>
							{% endif %}
					</div>
					{% else %}
						<div class="card-body">
							<div class="alert alert-danger">Item(s) not found</div>
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock  %}