coa/app/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views, item, sales

urlpatterns = [
    path('', views.login_view,name='login'),
    path('login', views.login_view,name='login'),
    path('logout', views.logout_view, name='logout'),
    path('dashboard', views.dashboard,name='dashboard'),
    path('statistics', views.statistics,name='statistics'),
    path('prediction', views.prediction,name='prediction'),
    path('preview', views.order_preview,name='order_preview'),
    path('place-order', views.order_place,name='order_place'),
    path('order-clear', views.order_clear,name='order_clear'),
    path('change-order-clear', views.change_order_status,name='change_order_status'),
    path('order/<str:token>', views.order_view,name='order_view'),
    path('order-download/<str:token>', views.order_download,name='order_download'),
    path('add-new-order', views.order_add_new,name='order_add_new'),
    path('add-new-order/preview', views.order_add_new_preview,name='order_add_new_preview'),
    path('add-new-order/generate', views.order_add_new_generate,name='order_add_new_generate'),
    path('history', views.order_history,name='order_history'),
    path('store', views.store,name='store'),
    path('generate_store_prediction_data', views.generate_store_prediction_data,name='generate_store_prediction_data'),
    path('change-chart/<str:token>/<int:cid>', views.change_chart_data, name='change_chart_data'),
    #get category's subcategories
    path('subcategories/<int:pk>', views.subcategories, name='subcategories'),
    #items
    path('item/listing', item.item_list, name='item_list'),
    path('item/status', item.change_item_status, name='change_item_status'),
    path('item/view/<str:token>', item.item_view, name='item_view'),
    path('item/new', item.item_create, name='item_new'),  
    path('item/edit/<str:token>', item.item_update, name='item_edit'),
    path('item/delete/<str:token>', item.item_delete, name='item_delete'),
    #sales data
    path('sales/listing', sales.sales_list, name='sales_list'),
    path('sales/status', sales.change_sales_status, name='change_sales_status'),
    path('sales/view/<int:pk>', sales.sales_view, name='sales_view'),
    path('sales/new', sales.sales_create, name='sales_new'),  
    path('sales/edit/<int:pk>', sales.sales_update, name='sales_edit'),
    path('sales/delete/<int:pk>', sales.sales_delete, name='sales_delete'),
    path('sales/import/upload', sales.sales_import_upload, name='sales_import_upload'),
    path('sales/import/list', sales.sales_import_list, name='sales_import_list'),
] 

coa/coa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coa/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, PermissionsMixin
from django.utils.translation import ugettext_lazy as _
import uuid
from django.contrib.auth.models import User
# from django.contrib.postgres.fields import JSONField
from django.db.models import JSONField

#Category Model
class Category(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    name        = models.CharField(max_length=255, unique=True)
    publish     = models.BooleanField(default = True)
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt   = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

#Sub Category Model
class Subcategory(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    category    = models.ForeignKey(Category, on_delete=models.CASCADE)
    name        = models.CharField(max_length=255)
    publish     = models.BooleanField(default = True)
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt   = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Sub Category'
        verbose_name_plural = 'Sub Categories'

#Family Model
class Family(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    name        = models.CharField(max_length=255, unique=True)
    publish     = models.BooleanField(default = True)
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt   = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Family'
        verbose_name_plural = 'Families'

#Store Model
class Store(models.Model):
    token           = models.UUIDField(default= uuid.uuid4)
    user            = models.ForeignKey(User, on_delete=models.CASCADE)
    name            = models.CharField(max_length=255)
    address         = models.CharField(max_length=255)
    city            = models.CharField(max_length=255)
    state           = models.CharField(max_length=255)
    zipcode         = models.CharField(max_length=255)
    phone           = models.CharField(max_length=255,blank = True, null=True)
    publish         = models.BooleanField(default = True)
    createdAt       = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt       = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Store'
        verbose_name_plural = 'Stores'

#Supplier Model
class Supplier(models.Model):
    token           = models.UUIDField(default= uuid.uuid4)
    name            = models.CharField(max_length=255)
    address         = models.CharField(max_length=255)
    city            = models.CharField(max_length=255)
    state           = models.CharField(max_length=255)
    zipcode         = models.CharField(max_length=255)
    email           = models.EmailField(max_length=255)
    phone           = models.CharField(max_length=255,blank = True, null=True)
    moq             = models.FloatField(blank = True, null=True)
    publish         = models.BooleanField(default = True)
    createdAt       = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt       = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Supplier'
        verbose_name_plural = 'Suppliers'

#Item Model
class Item(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    store       = models.ForeignKey(Store, on_delete=models.CASCADE)
    image       = models.ImageField(null=True, blank=True, upload_to="items/")
    category    = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    supplier    = models.ForeignKey(Supplier, on_delete=models.CASCADE, blank = True, null=True)
    name        = models.CharField(max_length=255)
    sku         = models.CharField(max_length=255)
    price       = models.FloatField()
    moq         = models.IntegerField(blank = True, null=True, default=1)
    uom         = models.CharField(max_length=255, choices=(('mm','Millimeter'),('cm','Centimeters'),('m','Meter'),('mg','Milligram'),('g','Gram'),('kg','Kilograms'),('mel','Milliliter'),('l','Liter'),('q','Quantity')), blank = True, null=True)
    publish     = models.BooleanField(default = True)
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt   = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Items'

#Sales Data Model
class Sales(models.Model):
    item        = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity    = models.IntegerField()
    revenue     = models.FloatField(blank = True, null=True)
    updatedOn   = models.DateField()
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.item.name

    class Meta:
        verbose_name = 'Sales Data'
        verbose_name_plural = 'Sales Datas'

#Stock Data Model
class Stock(models.Model):
    item        = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity    = models.IntegerField()
    updatedOn   = models.DateField()
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return self.item.name

    class Meta:
        verbose_name = 'Stock Data'
        verbose_name_plural = 'Stock Datas'


#Store charts
class Salescharts(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    store       = models.ForeignKey(Store, on_delete=models.CASCADE)
    chart1      = JSONField(null=True, blank = True)
    chart2      = JSONField(null=True, blank = True)
    chart3      = JSONField(null=True, blank = True)
    chart4      = JSONField(null=True, blank = True)
    chart5      = JSONField(null=True, blank = True)
    chart6      = JSONField(null=True, blank = True)
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    updatedAt   = models.DateTimeField(auto_now=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return str(self.store)

    class Meta:
        verbose_name = 'Sales Chart'
        verbose_name_plural = 'Sales Charts'

#Weekly Sales Data Model
class WeeklySales(models.Model):
    token       = models.UUIDField(default= uuid.uuid4)
    store       = models.ForeignKey(Store, on_delete=models.CASCADE)
    category    = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    mon         = models.FloatField()
    tue         = models.FloatField()
    wed         = models.FloatField()
    thu         = models.FloatField()
    fri         = models.FloatField()
    sat         = models.FloatField()
    sun         = models.FloatField()
    tot         = models.FloatField()
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return str(self.store)+' - '+str(self.category)+' - '+str(self.subcategory)+' - '+str(self.createdAt)

    class Meta:
        verbose_name = 'Weekly Sales Data'
        verbose_name_plural = 'Weekly Sales Data'

#Weekly Item Avg Data
class WeeklyItemsAvg(models.Model):
    salesweek   = models.ForeignKey(WeeklySales, on_delete=models.CASCADE)
    item        = models.ForeignKey(Item, on_delete=models.CASCADE)
    avg         = models.FloatField()
    ratio       = models.FloatField()
    mon         = models.FloatField()
    tue         = models.FloatField()
    wed         = models.FloatField()
    thu         = models.FloatField()
    fri         = models.FloatField()
    sat         = models.FloatField()
    sun         = models.FloatField()
    createdAt   = models.DateTimeField(auto_now_add=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return str(self.item)

    class Meta:
        verbose_name = 'Item Weekly Avg'
        verbose_name_plural = 'Item Weekly Avg'

#Order Model
class Order(models.Model):
    token           = models.UUIDField(default= uuid.uuid4)
    store           = models.ForeignKey(Store, on_delete=models.CASCADE)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory     = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    is_placed       = models.BooleanField(default = False)
    activate_day    = models.CharField(max_length=255)
    order_type      = models.CharField(max_length=255, choices=(('Prediction','Prediction'),('Custom','Custom')),default = 'Prediction')
    createdAt       = models.DateTimeField(auto_now_add=True, null=True)
    
    def __int__(self):
        return self.id
    
    def __str__(self):
        return str(self.store)+' - '+str(self.category)+' - '+str(self.subcategory)+' - '+str(self.createdAt)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

#Order Item Model
class OrederItem(models.Model):
    order           = models.ForeignKey(Order, on_delete=models.CASCADE)

coa/templates/order/history.html
{% extends "base.html" %}

{% block title %}Place Order{% endblock %}

{% block pagetitle %}Place Order{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<li class="breadcrumb-item active">Place Order</li>
{% endblock %}

{% load static %}

{% block content %}
<section class="content">
	<div class="container-fluid">
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == 'error' %}
				<div class="alert alert-danger">{{ message|safe }}</div><br/>
				{% else%}
				<div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div><br/>
				{% endif %}
			{% endfor %}
		{% endif %}

		<div class="row">
				<div class="col-12">
		<div class="card">
				<div class="card-header">
					<h3 class="card-title">Filter</h3>
					<div class="card-tools">
						<button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
						  <i class="fas fa-minus"></i></button>
					</div>
				</div>
				<!-- /.card-header -->
				<div class="card-body">
					<form role="form" method="POST" id="filter_item_form">
					{% csrf_token %}
					<div class="row">
						<div class="col-sm-3">
							<!-- select -->
							<div class="form-group">
								<label>Category</label>
								<select class="custom-select" name="category" id="id_category">
								<option value="">-- Select Category --</option>
								{% for cat in categories%}
									<option value="{{cat.id}}" {% if order_Post.category|slugify == cat.id|slugify %} selected {% endif %}>{{cat.name}}</option>
								{% endfor %}
								</select>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label>Sub Category</label>
								<select class="custom-select" name="subcategory" id="id_subcategory">
								<option value="">-- Select Sub Category --</option>
								{% for sub in subcategories %}
									<option value="{{sub.id}}" {% if order_Post.subcategory|slugify == sub.id|slugify %} selected {% endif %}>{{sub.name}}</option>
								{% endfor %}
								</select>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label>Supplier</label>
								<select class="custom-select" name="supplier" id="id_supplier">
								<option value="">-- Select Supplier --</option>
								{% for supplier in suppliers %}
									<option value="{{supplier.id}}" {% if order_Post.supplier|slugify == supplier.id|slugify %} selected {% endif %}>{{supplier.name}}</option>
								{% endfor %}
								</select>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group" style="margin-top:30px;">
								<button type="button" class="btn btn-info" onclick="ItemFormSeach('search');">Search</button>
								<button type="button" class="btn btn-default" onclick="ItemFormSeach('clear');">Clear</button>
								<input type="hidden" name="search_action" id="search_action" value="search">
							</div>
						</div>
					</div>
				</form>
				</div>
				<!-- /.card-body -->
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Order Listing</h3> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						<div class="btn-group" id="action_btn" style="display:none">
							<button type="button" class="btn btn-default">Action</button>
							<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
							</button>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item"  href="javascript:ActionPlaceOrder('delete')">Placed Selected Orders</a></li>
							</ul>
						</div>
						<div class="card-tools">
							<a href="{% url 'order_add_new' %}" class="btn btn-block btn-primary"><i class="fas fa-plus"></i> &nbsp Create Adhoc Order</a>
					   </div>
					</div>
					<!-- /.card-header -->
					{% if object_list %}
					<div class="card-body table-responsive">
						<form method="POST" id="form_list" action="{% url 'change_order_status' %}">
							{% csrf_token %}
							<table id="item_list" class="table table-bordered table-striped">
								<thead>
								<tr class="bg-primary">
									<th class="text-center"><input type="checkbox" name="chk_all" id="chk_all" value="all"></th>
									<th >Category</th>
									<th >Sub Category</th>
									<th class="text-center">Placed</th>
									<th class="text-center">Type</th>
									<th class="text-center">Date & Time</th>
									<th class="text-center">Action</th>
								</tr>
								</thead>
								<tbody>
									{% for order in object_list %}
										<tr>
											<td class="text-center">
												<input type="checkbox" id="id_{{order.token}}" name="records" class="chk" value="{{order.token}}">
											</td>

											<td >{{order.category}}</td>
											<td >{{order.subcategory}}</td>
											<td class="text-center"> 
												{% if order.is_placed %}
													<button type="button" class="btn btn-success btn-sm"><i class="fas fa-check"></i></button>
												{% else %}
													<button type="button" class="btn btn-danger btn-sm"><i class="fas fa-times"></i></button>
												{% endif %}
											</td>
											<td class="text-center">
												{% if order.order_type == 'Custom'%}
													Adhoc
												{% else %}
													Predicated
												{% endif %}
											</td> 
											<td class="text-center">{{order.createdAt}}</td>
											<td class="text-center">
												<a href="{% url 'order_view' order.token %}" class="btn btn-sm btn-secondary" title="View"><i class="fas fa-eye"></i> View</a>
												<a href="{% url 'order_download' order.token %}" class="btn btn-sm btn-primary" title="View"><i class="fas fa-download"></i> Download</a>
											</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
							<input type="hidden" name="action_on" id="action_on">
						</form>
					</div>
					<!-- /.card-body -->
					<div class="card-footer clearfix">

							{% if object_list.has_other_pages %}
							<ul class="pagination pagination-sm m-0 float-right">
								{% if object_list.has_previous %}
								<li class="page-item"><a class="page-link" href="?page={{ object_list.previous_page_number }}">&laquo;</a></li>
								{% else %}
								<li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
								{% endif %}
								{% for i in object_list.paginator.page_range %}
								{% if object_list.number == i %}
									<li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
								{% else %}
									<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
								{% endif %}
								{% endfor %}
								{% if object_list.has_next %}
								<li class="page-item"><a class="page-link" href="?page={{ object_list.next_page_number }}">&raquo;</a></li>
								{% else %}
								<li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
								{% endif %}
							</ul>
							{% endif %}
					</div>
					{% else %}
						<div class="card-body">
							<div class="alert alert-danger">order(s) not found</div>
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock  %}

coa/templates/order/statistics.html
{% extends "base.html" %}

{% block title %}Weekly Sales Outlook{% endblock %}

{% block pagetitle %}Weekly Sales Outlook{% endblock %}

{% block breadcrumbs %}
	{{ block.super }}
	<li class="breadcrumb-item active">Weekly Sales Outlook</li> 
{% endblock %}

{% load static %}

{% block content %}

<!-- Main content -->
<section class="content">
	<div class="container-fluid">

		{% if messages %}
			{% for message in messages %}
				{% if message.tags == 'error' %}
				<div class="alert alert-danger">{{ message|safe }}</div><br/>
				{% else%}
				<div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div><br/>
				{% endif %}
			{% endfor %}
		{% endif %}
		

		<div class="row">
			<div class="col-12">
	<div class="card">
			<div class="card-header">
				<h3 class="card-title">Generate Sales Prediction Data</h3>
				<div class="card-tools">
					<button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
					  <i class="fas fa-minus"></i></button>
				</div>
			</div>
			<!-- /.card-header -->
			<div class="card-body">
				<div class="row">
					<div class="col-sm-5">
						<div class="form-group">
							<label>Model</label>
							<select class="custom-select" name="model" id="id_model">
								<option value="">-- Select Model --</option>
								<option value="MA">Moving Average - MA</option>
								<option value="ARIMA">Autoregressive Integrated Moving Average - ARIMA</option>
								<option value="SARIMA">Seasonal Autoregressive Integrated Moving Average - SARIMA</option>
								<option value="LSTM">Long Short Term Memory Network - LSTM</option>
							</select>
						</div>
					</div>
					<div class="col-sm-5">
						<div class="form-group">
							<label>Factors</label>
							<div class="form-check">
							  <input class="form-check-input" type="checkbox" id="factors_1">
							  <label class="form-check-label" for="factors_1">Seasonal Factor</label>
							</div>
							<div class="form-check">
							  <input class="form-check-input" type="checkbox" id="factors_2">
							  <label class="form-check-label" for="factors_2">Weather Factor</label>
							</div>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="form-group" style="margin-top:30px;">
							<a href="{% url 'generate_store_prediction_data' %}" class="btn btn-info">&nbsp Generate</a>
						</div>
					</div>
				</div>
			</div>
			<!-- /.card-body -->
			</div>
		</div>
		</div>


		{% if charts %}
		<div class="alert alert-info"> <i class="fas fa-info"></i> Total Weekly Sales <b>${{charts.chart2.summary1.value|floatformat:2}}</b></div>
		{% endif %}

		<div class="row">
			<div class="col-12">
	<div class="card">
			<div class="card-header">
				<h3 class="card-title">Filter</h3>
				<div class="card-tools">
					<button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
					  <i class="fas fa-minus"></i></button>
				</div>
			</div>
			<!-- /.card-header -->
			<div class="card-body">
				<form role="form" method="POST" id="filter_item_form">
				{% csrf_token %}
				<div class="row">
					
					<div class="col-sm-5">
						<!-- select -->
						<div class="form-group">
							<label>Category</label>
							<select class="custom-select" name="category" id="id_category">
							<option value="">-- Select Category --</option>
							{% for cat in categories%}
								<option value="{{cat.id}}" {% if statistics_Post.category|slugify == cat.id|slugify %} selected {% endif %}>{{cat.name}}</option>
							{% endfor %}
							
							</select>
						</div>
					</div>
					<div class="col-sm-5">
					<div class="form-group">
						<label>Sub Category</label>
						<select class="custom-select" name="subcategory" id="id_subcategory">
						<option value="">-- Select Sub Category --</option>
						{% for sub in subcategories %}
							<option value="{{sub.id}}" {% if statistics_Post.subcategory|slugify == sub.id|slugify %} selected {% endif %}>{{sub.name}}</option>
						{% endfor %}
						</select>
					</div>
					</div>
				<div class="col-sm-2">
					<div class="form-group" style="margin-top:30px;">
						<button type="button" class="btn btn-info" onclick="ItemFormSeach('search');">Search</button>
						<button type="button" class="btn btn-default" onclick="ItemFormSeach('clear');">Clear</button>
						<input type="hidden" name="search_action" id="search_action" value="search">
					</div>
				</div>
				</div>
			</form>
			</div>
			<!-- /.card-body -->
			</div>
		</div>
		</div>

		{% if object %}

		<div class="row">
			<div class="col-12">
				<div class="card">
				<!-- /.card-header -->
				<div class="card-body table-responsive p-0" style="height: 600px;">
					<table class="table table-bordered">
					<thead>
						<tr class="bg-primary">
							<th colspan="3">Category:{{sub_cat_info}}</th>
							<th class="text-center">Wed</th>
							<th class="text-center">Thu</th>
							<th class="text-center">Fri</th>
							<th class="text-center">Sat</th>
							<th class="text-center">Sun</th>
							<th class="text-center">Mon</th>
							<th class="text-center">Tue</th>
							<th></th>	
						</tr>
						<tr class="bg-primary">
							<th>Average weekly sales</th>
							<th>${{object.tot|floatformat:2}}</th>
							<th></th>
							<th class="text-center">${{object.wed|floatformat:2}}</th>
							<th class="text-center">${{object.thu|floatformat:2}}</th>
							<th class="text-center">${{object.fri|floatformat:2}}</th>
							<th class="text-center">${{object.sat|floatformat:2}}</th>
							<th class="text-center">${{object.sun|floatformat:2}}</th>
							<th class="text-center">${{object.mon|floatformat:2}}</th>
							<th class="text-center">${{object.tue|floatformat:2}}</th>
							<th class="text-center">${{object.tot|floatformat:2}}</th>
						</tr>
						<tr class="bg-primary">
							<th>SKU</th>
							<th class="text-center">Avg movement</th>
							<th class="text-center">SKU to Sales Ratio</th>
							<th colspan="8"></th>
						</tr>
					</thead>
					<tbody>
						{% for record in object.weeklyitemsavg_set.all %}
						<tr>
							<td>{{record.item.name}}</td>
							<td class="text-center">{{record.avg|floatformat:2}}</td>
							<td class="text-center">{{record.ratio|floatformat:4}}</td>
							<td class="text-center">{{record.wed|floatformat:2}}</td>
							<td class="text-center">{{record.thu|floatformat:2}}</td>
							<td class="text-center">{{record.fri|floatformat:2}}</td>
							<td class="text-center">{{record.sat|floatformat:2}}</td>
							<td class="text-center">{{record.sun|floatformat:2}}</td>
							<td class="text-center">{{record.mon|floatformat:2}}</td>
							<td class="text-center">{{record.tue|floatformat:2}}</td>
						</tr>
						{% endfor %}
					</tbody>
					<tfoot>
						<tr>
							<td></td>
							<th class="text-center">{{object.total_avg|floatformat:2}}</th>
							<th class="text-center">{{object.total_ratio|floatformat:4}}</th>
							<td class="text-center" colspan="8"></td>
						</tr>
					</tfoot>
					</table>
				</div>
				<!-- /.card-body -->
				</div>
				<!-- /.card -->
			</div>
		</div>
		{% else %}

			{% if statistics_Post %}

				<div class="row">
					<div class="col-12">
						<div class="card">
							<div class="card-body">
								<div class="alert alert-danger">Data not found</div>
							</div>
						</div>
					</div>
				</div>
				
			{% endif %}

		{% endif %}

	</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
	  

{% endblock  %}